---
# Primary RKE2 server configuration parameters. Remove the curly braces ( {} ) and add your configuration.
# See https://docs.rke2.io/install/install_options/server_config/ for all configuration options.
#rke2_config: {}
ansible_user: marth

# Example of possible rke2_config.
rke2_config:
  selinux: true
  #etcd-s3: true
  #etcd-s3-endpoint: "{{ vault_etcd_s3_endpoint }}"
  #etcd-s3-bucket: "{{ vault_etcd_s3_bucket }}"
  #etcd-s3-access-key: "{{ vault_etcd_s3_access_key }}"
  #etcd-s3-secret-key: "{{ vault_etcd_s3_secret_key }}"
  etcd-snapshot-schedule-cron: "0 */2 * * *"
  etcd-snapshot-retention: 56
#  profile: cis-1.6
  disable:
    - rke2-ingress-nginx
    - rke2-calico
  cni:
    - cilium
#  kube-controller-manager-arg:
#  - "tls-min-version=VersionTLS12"
#  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
#  kube-scheduler-arg:
#  - "tls-min-version=VersionTLS12"
#  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
#  kube-apiserver-arg:
#  - "tls-min-version=VersionTLS12"
#  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
#  - "request-timeout=300s"
  # Enable only when auditing is enabled, blocks API when audit fails
  #- "audit-log-mode=blocking-strict"

#  kubelet-arg:
#  - "feature-gates=DynamicKubeletConfig=false"
#  - "protect-kernel-defaults=true"
#  - "streaming-connection-idle-timeout=5m"
#
#  # Available in RKE2 1.21
#  etcd-extra-env:
#  - "ETCD_AUTO_TLS=false"
#  - "ETCD_PEER_AUTO_TLS=false"
#
  write-kubeconfig-mode: "0640"
  tls-san:
    - rke2-1.budapest.marthy.xyz
    - 192.168.10.211

# See https://kubernetes.io/docs/tasks/debug-application-cluster/audit/
# Add a policy configuration file by specifying the file path on the control host
# audit_policy_config_file_path: "{{ playbook_dir }}/sample_files/audit-policy.yaml"

# See https://docs.rke2.io/install/containerd_registry_configuration/
# Add a registry configuration file by specifying the file path on the control host
# registry_config_file_path: "{{ playbook_dir }}/sample_files/registries.yaml"

# See https://docs.rke2.io/helm/#automatically-deploying-manifests-and-helm-charts
# Add manifest files by specifying the directory path on the control host
manifest_config_file_path: "{{ inventory_dir }}/manifest/"
